
# Regular example

cgrid:
  type: regular
  mdc: 36
  flow: 0.04
  fhigh: 0.4
  xlenc: 100.0
  ylenc: 100.0
  mxc: 10
  myc: 10

inpgrid:
  - type: regular
    inpgrid: bottom
    xpinp: 0.0
    ypinp: 0.0
    alpinp: 0.0
    mxinp: 10
    myinp: 10
    dxinp: 0.1
    dyinp: 0.1
    excval: -999.0
  - type: regular
    inpgrid: wind
    xpinp: 0.0
    ypinp: 0.0
    alpinp: 0.0
    mxinp: 10
    myinp: 10
    dxinp: 0.1
    dyinp: 0.1
    excval: -999.0
    nonstationary:
      tbeg: '2023-01-01T00:00:00'
      delt: PT30M
      tend: '2023-02-01T00:00:00'
      deltfmt: hr

# Curvilinear example
cgrid_curvilinear:
  type: curvilinear
  mdc: 36
  flow: 0.04
  fhigh: 0.4
  mxc: 10
  myc: 10
  fname: grid_coord.txt

inpgrid_curvilinear:
  - type: curvilinear
    inpgrid: bottom
    mxinp: 10
    myinp: 10
    excval: -999.0
    nonstationary:
      tbeg: '2023-01-01T00:00:00'
      delt: PT30M
      tend: '2023-02-01T00:00:00'
      deltfmt: hr